stages:
  - build
  - deploy

variables:
  APP_NAME: authorization-api
  NOMAD_ADDR: "http://127.0.0.1:4646"
  IMAGE_TAG: "latest"

build-api:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_REGISTRY:$IMAGE_TAG .
    - echo "Pushing image to GitLab registry..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" "$DOCKER_REGISTRY"
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  only:
    - main
  tags:
   - api-runner

deploy-api:
  stage: deploy
  image: curlimages/curl:latest
  script:
    - echo "Deploying Authorization API to Nomad..."
    - curl -X POST --data @nomad_job.hcl $NOMAD_ADDR/v1/jobs
  only:
    - main
  tags:
   - api-runner

